# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: mirror
on:
  push:
  workflow_dispatch:
concurrency:
  group: mirror
jobs:
  github:
    runs-on: self-hosted
    steps:
      - run: apk add git openssh
      - name: Set up SSH key
        run: |
          install -m 700 -d ~/.ssh
          install -m 600 <(echo "${DEPLOY_KEY}") ~/.ssh/id_ed25519
          ssh-keyscan github.com tangled.org >> ~/.ssh/known_hosts
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      - name: Prune and mirror
        run: |
          git clone --mirror "https://${GITEA_TOKEN}@${GITHUB_SERVER_URL#https://}/${GITHUB_REPOSITORY}.git" css.git
          git -C css.git for-each-ref --format='delete %(refname)' refs/pull | git -C css.git update-ref --stdin
          git -C css.git push --mirror git@github.com:kou029w/css.git
          git -C css.git push --mirror git@tangled.org:did:plc:lqyo5wfetrysf5cbudqhpd4h
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
